version: "3.8"

services:
  xray:
    build: .
    container_name: xray-vless
    restart: unless-stopped
    environment:
      - UUID=${UUID}
      - WS_PATH=${WS_PATH:-/ws}
    volumes:
      - ./config/config.template.json:/etc/xray/config.template.json:ro
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      # HTTPS роутинг
      - "traefik.http.routers.xray.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.xray.entrypoints=websecure"
      - "traefik.http.routers.xray.tls=true"
      - "traefik.http.routers.xray.tls.certresolver=letsencrypt"
      # Сервис
      - "traefik.http.services.xray.loadbalancer.server.port=8080"

networks:
  dokploy-network:
    external: true
